name: tec_me_subes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Downgraded to stable version

flutter:
  uses-material-design: true
  assets:
    - assets/ITP.png
    - assets/TecMeSubes.jpg